# 모듈(라이브러리)

 - 확장자가 .py인 파일

- 함수, 클래스 혹은 변수들을 모아놓은 파일

- 파이썬 프로그램에서 불러와 사용할 수 있게끔 만들어진 파이썬 파일이라고도 한다.

# 분석에 특화된 모듈(라이브러리)

- Numpy : 고성능 과학계산을 위한 데이터 분석 라이브러리

- Pandas : 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리

# Numpy의 주요 기능

- **빠르고 효율적인 벡터 산술연산을 제공하는 다차원배열 제공**

    배열 : 파이선 List 문법과 비슷하게 여러 개의 데이터를 하나로 묶어서 관리하는 자료구조. 

    배열을 만들어 사용하기 위해서는 ndarray 클래스 사용해야 함

- **반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수**

    반복문을 사용하지 않고도 배열 안의 데이터들에 일괄적으로 수학계산 가능 (sum(), mean(), sqrt(), etc)

- **Numpy 수학 함수를 사용하기 위해서는 반드시 ndarray 클래스를 이용해서 배열을 만들어야 함.**

# 모듈(라이브러리) 사용하기

- numpy 모듈을 import 해준다

In [4]:
import numpy as np

# numpy.ndarray 클래스

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함 (숫자는 숫자끼리, 문자는 문자끼리)
- N 차원 형태로 구성이 가능하다
- 각 값들은 양의 정수(0 ~ )로 색인(index)이 부여되어 있다
- ndarray를 줄여서 array로 표현한다

### <span style="color:blue"> array 생성 하기 : 1차원 </span>

In [5]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

- ↓ **array를 쓸 때는 변수를 활용하거나**

In [8]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

- ↓ **리스트를 그대로 넣어도 된다**

In [9]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

### <span style="color:blue"> array 생성 하기 : 2차원 <span>

In [10]:
list2 = [6,7,8,9,10]
arr2 = np.array([list, list2])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### <span style="color:blue"> 배역의 크기 확인하기 <span>

In [12]:
arr.shape

(5,)

In [13]:
arr2.shape

(2, 5)

- ↑ **튜플 형태로 표시해 줌.**
- **arr2.shape (2, 5) = 2개의 행에 5개의 열이 있다.**

### <span style="color:blue"> 배열의 전체 요소 개수 확인하기 <span>

In [14]:
arr.size

5

In [15]:
arr2.size

10

### <span style="color:blue"> 배열의 타입 확인하기 <span>

In [16]:
arr.dtype

dtype('int32')

### <span style="color:blue"> 배열의 차원 확인하기 <span>

In [18]:
arr.ndim

1

In [19]:
arr2.ndim

2