In [4]:
import numpy as np

### <span style="color:blue"> 특정한 값으로 배열 생성하기 <span>

- **↓ 0으로 초기화 np.zeros()**
- **3행 4열 크기의 array 생성**

In [3]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- **↓ 1로도 가능 np.ones()**

In [5]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- **↓ 특정한 값으로 배열 생성하기 np.full()**
- **np.full((행,열),값)**

In [7]:
arr_full = np.full((5,5),7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

- **↓ 1 ~ 50 이 담긴 배열 생성하기**
- **np.arange(시작값, 끝값)**

In [13]:
arr_range = np.arange(1,51)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [23]:
arr_range2 = np.arange(1,50,2)
arr_range2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

- **↓ 랜덤 값 배열 생성하기**
- **np.random.rand(행,열)**
- **random.rand : 0 ~ 1 사이의 소수**

In [28]:
arr_random = np.random.rand(2,3)
arr_random

array([[0.06229928, 0.11843023, 0.4799705 ],
       [0.63640049, 0.48737588, 0.61564006]])

- **↓ random.randint(x, y) : x ~ y 사이의 랜덤한 정수 1개 생성**
- **np.random.randint(x, y, size(행,열))**

In [35]:
arr_randint = np.random.randint(1,100)
arr_randint

21

In [36]:
arr_randint3 = np.random.randint(1,100, size = (2,3))
arr_randint3

array([[12, 31, 14],
       [71,  1, 27]])

# Array Operation (연산)

### <span style="color:blue"> array 연산 (요소별 연산) <span>

- **연산할 때는 각 요소별로 연산된다**
- **단, 데이터의 사이즈가 같아야한다**

In [40]:
arr = np.array([1,2,3])
arr2 = np.array([1,1,1])

In [42]:
arr + arr2

array([2, 3, 4])

In [43]:
arr * arr2

array([1, 2, 3])