# Universal Function

### <span style="color:blue"> sum, mean 함수

In [1]:
import numpy as np

In [21]:
arr = np.random.randint(1,10, size = (5,5))
arr

array([[4, 6, 1, 5, 4],
       [1, 5, 8, 1, 2],
       [4, 1, 9, 8, 1],
       [8, 3, 1, 4, 4],
       [5, 7, 6, 2, 9]])

**Sum() = 총합**

In [22]:
arr.sum()

109

In [23]:
arr[0].sum()

20

**mean() = 평균**

In [24]:
arr.mean()

4.36

### <span style="color:blue"> abs 함수

**abs() = 절대값 absolute**

In [19]:
arr2 = np.array([-1,2,-3,4,-5])
np.abs(arr2)

array([1, 2, 3, 4, 5])

In [25]:
arr[2]

array([4, 1, 9, 8, 1])

In [26]:
arr[:,2]

array([1, 8, 9, 1, 6])