# Boolean 색인

### <span style="color:blue"> "참(True)"인 정보만 추출하기

In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
arr[[True, True, False]]

array([1, 2])

**↓ 예제 : 성적 80점 이상인 사람 구분**

In [22]:
score = np.array(np.random.randint(50, 100, size=8))
score

array([80, 67, 69, 62, 97, 74, 64, 61])

In [23]:
score_bool = score>=80
score_bool

array([ True, False, False, False,  True, False, False, False])

In [24]:
score80 = score[score_bool]
score80

array([80, 97])

**↓ 2차원 배열 예제**

In [52]:
score2 = [54, 91, 100, 85, 76]
name2 = ['A','B','C','D','E']
score_name = np.array([name2, score2])
score_name

array([['A', 'B', 'C', 'D', 'E'],
       ['54', '91', '100', '85', '76']], dtype='<U3')

In [54]:
score_name.T

array([['A', '54'],
       ['B', '91'],
       ['C', '100'],
       ['D', '85'],
       ['E', '76']], dtype='<U3')

In [58]:
Pass = score_name[1].astype(int) >= 80
score_name.T[Pass]

array([['B', '91'],
       ['C', '100'],
       ['D', '85']], dtype='<U3')

### <span style="color:blue"> 기타 기능

**행 순서 바꾸기**

In [60]:
score_name[[1,0]]

array([['54', '91', '100', '85', '76'],
       ['A', 'B', 'C', 'D', 'E']], dtype='<U3')

**행/열 변경**

In [71]:
score_name.T

array([['A', '54'],
       ['B', '91'],
       ['C', '100'],
       ['D', '85'],
       ['E', '76']], dtype='<U3')